media_folder: "static/images/uploads"
backend:
  name: github
  repo: chir263/test-exp
  branch: master

collections:
  - name: "Experiment"
    label: "Experiment"
    folder: "/experiment"
    create: true
    slug: "experiment"
    delete: false
    fields: 
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
        